const Currencies = [
  { name: "United States Dollar", code: "USD", symbol: "$" },
  { name: "Euro", code: "EUR", symbol: "€" },
  { name: "Japanese Yen", code: "JPY", symbol: "¥" },
  { name: "British Pound", code: "GBP", symbol: "£" },
  { name: "Swiss Franc", code: "CHF", symbol: "CHF" },
  { name: "Canadian Dollar", code: "CAD", symbol: "$" },
  { name: "Australian Dollar", code: "AUD", symbol: "$" },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
  { name: "Indian Rupee", code: "INR", symbol: "₹" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "Mexican Peso", code: "MXN", symbol: "$" },
  { name: "Singapore Dollar", code: "SGD", symbol: "$" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "$" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "South Korean Won", code: "KRW", symbol: "₩" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Danish Krone", code: "DKK", symbol: "kr" },
  { name: "Polish Złoty", code: "PLN", symbol: "zł" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺" },
  { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
  { name: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ" },
  { name: "Argentine Peso", code: "ARS", symbol: "$" },
  { name: "Thai Baht", code: "THB", symbol: "฿" },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Philippine Peso", code: "PHP", symbol: "₱" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Egyptian Pound", code: "EGP", symbol: "£" },
  { name: "Colombian Peso", code: "COP", symbol: "$" },
  { name: "Chilean Peso", code: "CLP", symbol: "$" },
  { name: "Saudi Riyal", code: "SAR", symbol: "﷼" },
  { name: "Pakistani Rupee", code: "PKR", symbol: "₨" },
  { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
  { name: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
  { name: "Vietnamese Đồng", code: "VND", symbol: "₫" },
  { name: "Romanian Leu", code: "RON", symbol: "lei" },
  { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
  { name: "Peruvian Sol", code: "PEN", symbol: "S/" },
  { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
  { name: "Qatari Riyal", code: "QAR", symbol: "﷼" },
  { name: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
  { name: "Uruguayan Peso", code: "UYU", symbol: "$U" },
  { name: "Costa Rican Colón", code: "CRC", symbol: "₡" },
  { name: "Bulgarian Lev", code: "BGN", symbol: "лв" },
  { name: "Croatian Kuna", code: "HRK", symbol: "kn" },
  { name: "Icelandic Króna", code: "ISK", symbol: "kr" },
  { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
  { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
  { name: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
  { name: "Omani Rial", code: "OMR", symbol: "﷼" },
  { name: "Sri Lankan Rupee", code: "LKR", symbol: "₨" },
  { name: "New Taiwan Dollar", code: "TWD", symbol: "NT$" },
  { name: "Dominican Peso", code: "DOP", symbol: "RD$" },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
  { name: "Serbian Dinar", code: "RSD", symbol: "дин." },
  { name: "Tunisian Dinar", code: "TND", symbol: "د.ت" },
  { name: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
  { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs." },
  { name: "Paraguayan Guaraní", code: "PYG", symbol: "₲" },
  { name: "Macanese Pataca", code: "MOP", symbol: "MOP$" },
  { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
  { name: "Honduran Lempira", code: "HNL", symbol: "L" },
  { name: "Jamaican Dollar", code: "JMD", symbol: "J$" },
  { name: "Namibian Dollar", code: "NAD", symbol: "$" },
  { name: "Cambodian Riel", code: "KHR", symbol: "៛" },
  { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
  { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
  { name: "Belarusian Ruble", code: "BYN", symbol: "Br" },
  { name: "Venezuelan Bolívar", code: "VES", symbol: "Bs." },
  { name: "Moldovan Leu", code: "MDL", symbol: "L" },
  { name: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
  { name: "Mauritian Rupee", code: "MUR", symbol: "₨" },
  { name: "Armenian Dram", code: "AMD", symbol: "֏" },
  { name: "Seychellois Rupee", code: "SCR", symbol: "₨" },
  { name: "Fijian Dollar", code: "FJD", symbol: "FJ$" },
  { name: "Guyanese Dollar", code: "GYD", symbol: "G$" },
  { name: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf" },
  { name: "Ethiopian Birr", code: "ETB", symbol: "Br" },
  { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
  { name: "Nepalese Rupee", code: "NPR", symbol: "₨" },
  { name: "Bitcoin", code: "BTC", symbol: "₿" },
  { name: "Ethereum", code: "ETH", symbol: "Ξ" },
];

export default Currencies;